# Generated by Django 4.1.7 on 2023-03-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('In Progress', 'InProgress'), ('Make It In Feature', 'Make It In Feature'), ('Done', 'Done')], default='TODO', max_length=32)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.worker')),
            ],
        ),
    ]
